import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import LoanApplicationForm from "../components/LoanApplicationForm";
import ReviewLoanApplication from "../components/ReviewLoanApplication";
import SuccessPage from "../components/SuccessPage";

type AppStateType = "EDIT" | "REVIEW" | "SUBMITTED";
export type AccountingProviderType = "xero" | "myob";
export type FormData = {
  email: string;
  name: string;
  year: number;
  loanAmount: number;
  accountingProvider: AccountingProviderType;
};
type ApprovalData = {
  approved: boolean;
  amount: number;
};

const LoanApp: NextPage = () => {
  const [state, setState] = useState<AppStateType>("EDIT");
  const [data, setData] = useState<FormData>();
  const [approvalData, setApprovalData] = useState<ApprovalData>();

  const onReviewHandler = (formData: FormData) => {
    setData(formData);
    setState("REVIEW");
  };

  const onSubmitHandler = () => {
    setState("SUBMITTED");
    setApprovalData({ approved: true, amount: 5000 });
  };

  const onReset = () => {
    setState("EDIT");
  };

  return (
    <div>
      <Head>
        <title>Loan App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center align-middle bg-gray-200 h-screen">
        {state === "EDIT" ? (
          <LoanApplicationForm onReview={onReviewHandler} />
        ) : null}
        {state === "REVIEW" ? (
          <ReviewLoanApplication formData={data} onSubmit={onSubmitHandler} />
        ) : null}
        {state === "SUBMITTED" ? (
          <SuccessPage
            approved={approvalData?.approved}
            amount={approvalData?.amount}
            onReset={onReset}
          />
        ) : null}
      </main>
    </div>
  );
};

export default LoanApp;
